AWSTemplateFormatVersion: 2010-09-09
Description: "Media Insights Engine - Analytics Streaming pipeline from the Dataplane DynamoDB Stream"

Parameters:
  KinesisShardCount:
    Type: Number
    Default: 1
  DynamoStreamArn:
    Type: String
    Description: "Arn of the Dataplane Dynamo DB Stream"
  DynamoTableArn:
    Type: String
    Description: "Arn of the Dataplane Dynamo DB table"
  DeployElasticConsumer:
    Type: String
    Description: "Do you want to deploy a data consumer that feeds into an Elasticsearch Cluster?"
    AllowedValues:
      - Yes
      - No
    Default: No
  DataplaneBucket:
    Type: String
    Description: "Dataplane bucket"
  MieAdminRole:
    Type: String

Mappings:
  SourceCode:
        General:
            GlobalS3Bucket: "%%GLOBAL_BUCKET_NAME%%"
            RegionalS3Bucket: "%%REGIONAL_BUCKET_NAME%%"
            CodeKeyPrefix: "aws-content-analysis/%%VERSION%%"
            TemplateKeyPrefix: "aws-content-analysis/%%VERSION%%"

Conditions:
  DeployESConsumer: !Equals [!Ref DeployElasticConsumer, Yes]

Resources:
# kinesis data stream

  AnalyticsStream:
    Type: "AWS::Kinesis::Stream"
    Properties:
      ShardCount: !Ref KinesisShardCount
      StreamEncryption:
        EncryptionType: "KMS"
        KeyId: "alias/aws/kinesis"

# ddb stream lambda

  DynamoDBStreamingFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      Handler: "stream.lambda_handler"
      Role: !GetAtt LambdaStreamRole.Arn
      Code:
        S3Bucket: !Join ["-", [!FindInMap ["SourceCode", "General", "RegionalS3Bucket"], Ref: "AWS::Region"]]
        S3Key:
          !Join [
            "/",
            [
              !FindInMap ["SourceCode", "General", "CodeKeyPrefix"],
              "ddbstream.zip",
            ],
          ]
      Runtime: "python3.7"
      Environment:
        Variables:
          StreamName: !Ref AnalyticsStream

# stream event mapping for lambda

  StreamingFunctionEventMapping:
    Type: "AWS::Lambda::EventSourceMapping"
    Properties:
      Enabled: true
      EventSourceArn: !Ref DynamoStreamArn
      FunctionName: !GetAtt DynamoDBStreamingFunction.Arn
      StartingPosition: "LATEST"

# iam stuff
  LambdaStreamRole:
    Type: "AWS::IAM::Role"
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W11
            reason: "Lambda requires ability to write to cloudwatch *, as configured in the default AWS lambda execution role."
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: !Sub "${AWS::StackName}-LambdaStreamAccessPolicy"
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - "kinesis:ListShards"
                  - "kinesis:DescribeStream"
                  - "kinesis:GetRecords"
                  - "kinesis:GetShardIterator"
                  - "kinesis:ListStreams"
                  - "kinesis:DescribeStreamSummary"
                  - "kinesis:PutRecord"
                  - "kinesis:PutRecords"
                Resource: !GetAtt AnalyticsStream.Arn
              - Effect: Allow
                Action:
                  - "dynamodb:DescribeStream"
                  - "dynamodb:GetRecords"
                  - "dynamodb:GetShardIterator"
                  - "dynamodb:ListStreams"
                Resource: !Ref DynamoStreamArn
              - Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "*"
  ElasticConsumer:
    Type: "AWS::CloudFormation::Stack"
    Condition: DeployESConsumer
    DependsOn:
      - AnalyticsStream
      - DynamoDBStreamingFunction
    Properties:
      TemplateURL:
        !Join [
          "/",
          [
            "https://s3.amazonaws.com",
            !FindInMap ["SourceCode", "General", "GlobalS3Bucket"],
            !FindInMap ["SourceCode", "General", "TemplateKeyPrefix"],
            "media-insights-elasticsearch.template",
          ],
        ]
      Parameters:
        AnalyticsStreamArn: !GetAtt AnalyticsStream.Arn
        MieDataplaneBucket: !Ref DataplaneBucket
        MIEAdminRoleArn: !Ref MieAdminRole

Outputs:
  ElasticUrl:
    Condition: DeployESConsumer
    Value: !GetAtt ElasticConsumer.Outputs.ElasticEndpoint
